server:
  port: 8002
#数据源配置
mybatis:
  #  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.sedin.microcloudapi
spring:
  application:
    name: microcloudproviderdept8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
#  security:                       #  springSecurity的安全配置
#    user:
#      name: chenhuan
#      password: root
#      roles: -USER

#日志设置
logging:
  level:
    com.sedin.microcloudproviderdept8002.dao: debug
#Eureka客户端注册到服务列表
eureka:
  client:
    service-url:
#      单机版
#      defaultZone: http://localhost:7001/eureka
#      集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microcloud-dept-8002        #显示服务名称
    prefer-ip-address: true                 #显示ip地址

info:
  app.name: microcloud
  company.name: www.sedin.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
