server:
  port: 8001
#数据源配置
mybatis:
  #  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.sedin.microcloudapi
spring:
  application:
    name: microcloudproviderdept8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  security:                       #  springSecurity的安全配置
    user:
      name: chenhuan
      password: chenhuan123!
      roles: -USER

#日志设置
logging:
  level:
    com.sedin.microcloudproviderdept8001.dao: debug
#Eureka客户端注册到服务列表
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
